name: Main Workflow

#on: [ push ]

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.2'
          channel: "stable"
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      #      - name: Install packages
      #        run: cd ert_lint && flutter pub get
      #      - name: Install packages
      #        run: cd ucp_lint && flutter pub get
      - name: Install packages
        run: flutter pub get
      - name: Linter
        continue-on-error: true
        run: flutter analyze --no-fatal-warnings --no-fatal-infos --no-pub
